### ISSUE TITLE
Fails to compile with rustc 1.43.0 

### ISSUE THREAD

**Issue by cburgmer** [mkmik/slyce#17]
I'm trying to compile https://github.com/jsonpath-standard/jsonpath-reference-implementation on Ubuntu 20.10, and am running into the following compile error:

```
error[E0308]: `if` and `else` have incompatible types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slyce-0.3.0/src/lib.rs:162:13
    |
159 |           let is_in_range = if self.step >= 0 {
    |  ___________________________-
160 | |             |a, b| a < b
    | |             ------------ expected because of this
161 | |         } else {
162 | |             |a, b| a > b
    | |             ^^^^^^^^^^^^ expected closure, found a different closure
163 | |         };
    | |_________- `if` and `else` have incompatible types
    |
    = note: expected type `[closure@/root/.cargo/registry/src/github.com-1ecc6299db9ec823/slyce-0.3.0/src/lib.rs:160:13: 160:25]`
            found closure `[closure@/root/.cargo/registry/src/github.com-1ecc6299db9ec823/slyce-0.3.0/src/lib.rs:162:13: 162:25]`
    = note: no two closures, even if identical, have the same type
    = help: consider boxing your closure and/or using it as a trait object
```

```
$ rustc --version
rustc 1.43.0
```

It compiles fine on OSX with rustc 1.47.0.

**Comment by glyn** [comment]
Any particular reason not to upgrade rust to the latest?

**Comment by cburgmer** [comment]
Currently Rust is installed via
```
RUN apt-get install -y --no-install-recommends cargo
```
which pulls in the regular package : https://packages.ubuntu.com/groovy/rustc.

I would have to install via other means to upgrade.

**Comment by glyn** [comment]
A simple change accommodated rust 1.43. It would be easy to regress this though, so let's see what @mkmik makes of the fix when he reviews it.

**Comment by mkmik** [comment]
Interesting thread: https://news.ycombinator.com/item?id=25594057

Since this is a very small crate, it's not hard for me to ensure this works on 1.43 for a while, but you're likely to encounter other problems if you keep using the distribution provided version. The rust ecosystem seems to assume that you kinda keep up with latest stable; the toolchain maintainers are committed at maintaining backward compat so it shouldn't be a problem

**Comment by cburgmer** [comment]
Thanks a lot, noted. If this comes up again, I'll try rustup instead.

**Comment by glyn** [comment]
> Thanks a lot, noted. If this comes up again, I'll try rustup instead.

It shouldn't come up by surprise since the reference implementation also tests against 1.43.0. Talking of which https://github.com/jsonpath-standard/jsonpath-reference-implementation/pull/25 is now merged.
